### PR TITLE
B23Sophie completed tc100

### PR DESCRIPTION
**Pull request by SophieGuven**
added new codes for login functionality
hope everything is ok

### CODE REVIEW

**Comment by furkannaktas** [comment]
nice code

**Comment by SophieGuven** [comment]
thanks @furkannaktas, you do also

**Review by KemalTolga — COMMENTED** [review]
Good Job!

**Review by furkannaktas — COMMENTED** [review]
u r doing your best

**Review by SophieGuven — COMMENTED** [review]
great job guys,

**Pull request merged**
