### PR TITLE
Furkan completed class

### PR DESCRIPTION
**Pull request by furkannaktas**
created new codes and completed the task

### CODE REVIEW

**Review by gabil89 — APPROVED** [review]
Good job

**Review by gabil89 — CHANGES_REQUESTED** [review]
Change line 15

**Review by SophieGuven — APPROVED** [review]
seems good

**Review by KemalTolga — APPROVED** [review]
Approved

**Review by Dolohodin — APPROVED** [review]

**Review by gabil89 — APPROVED** [review]
Good job

**Pull request merged**
