### PR TITLE
Log-Out function 

### PR DESCRIPTION
**Pull request by aliyevkhayyam**
our new project

### CODE REVIEW

**Review by furkannaktas — APPROVED** [review]
good

**Comment by KemalTolga** [comment]
cool

**Review by gabil89 — APPROVED** [review]
Good job

**Review by gabil89 — APPROVED** [review]
Good job guys

**Review by furkannaktas — APPROVED** [review]
nice code again

**Review by gabil89 — APPROVED** [review]

**Comment by aliyevkhayyam** [comment]
Everything looks good guys

**Comment by aliyevkhayyam** [comment]
finished

**Pull request merged**
