### PR TITLE
Kemal completed tc100

### PR DESCRIPTION
**Pull request by KemalTolga**
added automation for login functionality
did this did that

### CODE REVIEW

**Comment by furkannaktas** [comment]
good code

**Review by furkannaktas — APPROVED** [review]
lets merge this!

**Review by furkannaktas — APPROVED** [review]
approved!

**Comment by jamina17** [comment]
good job

**Review by aliyevkhayyam — COMMENTED** [review]
this is wooww

**Review by gabil89 — COMMENTED** [review]
Approved

**Pull request merged**
